In [14]:
import pandas as pd
import numpy as np
import random

In [15]:
df=pd.read_csv('../../dataset/kddcup.csv')
#adding a new column named result and assigning it to 1
df['result']=1

#displaying the first 5 rows of the dataset
print(df.head())

   0    1     2   3    4      5  6  7  8  9  ...   33   34    35   36   37  \
0  0  tcp  http  SF  215  45076  0  0  0  0  ...  0.0  0.0  0.00  0.0  0.0   
1  0  tcp  http  SF  162   4528  0  0  0  0  ...  1.0  0.0  1.00  0.0  0.0   
2  0  tcp  http  SF  236   1228  0  0  0  0  ...  1.0  0.0  0.50  0.0  0.0   
3  0  tcp  http  SF  233   2032  0  0  0  0  ...  1.0  0.0  0.33  0.0  0.0   
4  0  tcp  http  SF  239    486  0  0  0  0  ...  1.0  0.0  0.25  0.0  0.0   

    38   39   40       41  result  
0  0.0  0.0  0.0  normal.       1  
1  0.0  0.0  0.0  normal.       1  
2  0.0  0.0  0.0  normal.       1  
3  0.0  0.0  0.0  normal.       1  
4  0.0  0.0  0.0  normal.       1  

[5 rows x 43 columns]


In [16]:
print(df['1'].unique())
print(df['2'].unique())
print(df['3'].unique())
print(df['41'].unique())

['tcp' 'udp' 'icmp']
['http' 'smtp' 'domain_u' 'auth' 'finger' 'telnet' 'eco_i' 'ftp' 'ntp_u'
 'ecr_i' 'other' 'urp_i' 'private' 'pop_3' 'ftp_data' 'netstat' 'daytime'
 'ssh' 'echo' 'time' 'name' 'whois' 'domain' 'mtp' 'gopher' 'remote_job'
 'rje' 'ctf' 'supdup' 'link' 'systat' 'discard' 'X11' 'shell' 'login'
 'imap4' 'nntp' 'uucp' 'pm_dump' 'IRC' 'Z39_50' 'netbios_dgm' 'ldap'
 'sunrpc' 'courier' 'exec' 'bgp' 'csnet_ns' 'http_443' 'klogin' 'printer'
 'netbios_ssn' 'pop_2' 'nnsp' 'efs' 'hostnames' 'uucp_path' 'sql_net'
 'vmnet' 'iso_tsap' 'netbios_ns' 'kshell' 'urh_i' 'http_2784' 'harvest'
 'aol' 'tftp_u' 'http_8001' 'tim_i' 'red_i']
['SF' 'S2' 'S1' 'S3' 'OTH' 'REJ' 'RSTO' 'S0' 'RSTR' 'RSTOS0' 'SH']
['normal.' 'buffer_overflow.' 'loadmodule.' 'perl.' 'neptune.' 'smurf.'
 'guess_passwd.' 'pod.' 'teardrop.' 'portsweep.' 'ipsweep.' 'land.'
 'ftp_write.' 'back.' 'imap.' 'satan.' 'phf.' 'nmap.' 'multihop.'
 'warezmaster.' 'warezclient.' 'spy.' 'rootkit.']


In [17]:
from sklearn.preprocessing import LabelEncoder

#creating an object of the class LabelEncoder
le=LabelEncoder()
df['1']=le.fit_transform(df['1'])
df['2']=le.fit_transform(df['2'])
df['3']=le.fit_transform(df['3'])
df['41']=le.fit_transform(df['41'])

print(df['1'].unique())
print(df['2'].unique())
print(df['3'].unique())
print(df['41'].unique())

[1 2 0]
[24 54 12  4 18 60 14 19 43 15 44 65 49 47 20 40  9 56 13 63 36 69 11 35
 21 51 52  8 58 33 59 10  1 53 34 28 42 66 45  0  2 37 32 57  6 17  5  7
 26 30 48 39 46 41 16 23 67 55 68 29 38 31 64 25 22  3 61 27 62 50]
[ 9  7  6  8  0  1  2  5  4  3 10]
[11  1  7 12  9 18  3 14 20 15  5  6  2  0  4 17 13 10  8 22 21 19 16]


In [18]:
# randomly generating outliners for the dataset and assinging the result column to -1
len_columns=len(df.columns)
len_rows=len(df)
outliers=[]

min_cloumn_values=[]
max_cloumn_values=[]


for i in range(0,len_columns-1):
    min_cloumn_values.append(int(np.percentile(df.iloc[:,i],1)))
    max_cloumn_values.append(int(np.percentile(df.iloc[:,i],99))+.1)
print(min_cloumn_values)
print(max_cloumn_values)

for i in range(0,35):
    temp=[]
    scaling_factor=random.uniform(1,2)
    for j in range(0,len_columns-1):
        if max_cloumn_values[j]<=0:
            temp.append(int(min_cloumn_values[j]))
        else:
            temp.append(int(np.random.uniform(min_cloumn_values[j],max_cloumn_values[j])*scaling_factor))
    temp.append(-1)
    outliers.append(temp)

print(outliers)
print(len(outliers))

[0, 0, 12, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 9]
[66.1, 2.1, 54.1, 9.1, 1558.1, 12323.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 511.1, 511.1, 1.1, 1.1, 1.1, 1.1, 1.1, 0.1, 1.1, 255.1, 255.1, 1.1, 0.1, 1.1, 0.1, 1.1, 1.1, 1.1, 1.1, 18.1]
[[81, 1, 25, 13, 2726, 17615, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 535, 972, 2, 2, 2, 0, 0, 0, 0, 431, 160, 1, 0, 0, 0, 1, 1, 0, 1, 18, -1], [55, 1, 64, 8, 1208, 2298, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 421, 446, 1, 0, 0, 0, 0, 0, 0, 204, 255, 0, 0, 0, 0, 0, 1, 0, 1, 18, -1], [60, 0, 75, 5, 1808, 5728, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 292, 965, 0, 1, 1, 1, 0, 0, 1, 469, 293, 0, 0, 0, 0, 1, 1, 1, 0, 32, -1], [40, 0, 79, 11, 2339, 12688, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 392, 795, 0, 0, 0, 0, 0, 0, 0, 395, 137, 1, 0, 1, 0, 0, 0, 0, 1, 29, -1], [80, 1, 43, 9, 670, 8903, 0, 0, 0, 0, 0, 1

In [19]:
#adding outliers to the dataset and shuffling the dataset
for i in range(0,len(outliers)):
    df.loc[len_rows+i]=outliers[i]

df=df.sample(frac=1).reset_index(drop=True)
print(df.head())


   0  1   2  3     4  5  6  7  8  9  ...    33    34   35   36   37   38   39  \
0  0  0  15  9  1032  0  0  0  0  0  ...  1.00  0.00  1.0  0.0  0.0  0.0  0.0   
1  0  0  15  9  1032  0  0  0  0  0  ...  1.00  0.00  1.0  0.0  0.0  0.0  0.0   
2  0  1  49  5     0  0  0  0  0  0  ...  0.01  0.08  0.0  0.0  1.0  1.0  0.0   
3  0  0  15  9  1032  0  0  0  0  0  ...  1.00  0.00  1.0  0.0  0.0  0.0  0.0   
4  0  0  15  9  1032  0  0  0  0  0  ...  1.00  0.00  1.0  0.0  0.0  0.0  0.0   

    40  41  result  
0  0.0  18       1  
1  0.0  18       1  
2  0.0   9       1  
3  0.0  18       1  
4  0.0  18       1  

[5 rows x 43 columns]


In [20]:
#saving the dataset to a new csv file
df.to_csv('../generated_datasets/kdd99_with_outliers.csv',index=False)